info:
  application:
    name: USSDMxAprovisionamiento
    description: Sistema de aprovisionamiento para clientes USSD
    version: 1.0.0
    year: 2024
  vendor:
    name: Hacom S.A.C.
    address: Av. Los Constructores 1250, La Molina 15012
    city: Lima
    country: Peru
    phone: +51 995-864-234
    email: hacom@hacom-tech.com
    url: https://www.hacom-tech.com/
  license: https://www.hacom-tech.com/licenses/LICENSE-Tech-1.0.html

server:
  port: 11000

#app:
#  mongodbDatabase: ussdmx
  #mongodbUri: "mongodb://127.0.0.1:27017"
  #mongodbUri: "mongodb://root:123456@mongo_db:27017/hacomDb?authSource=admin"
#  mongodbUri: "mongodb://admin:rw,.12a@192.168.5.128:27017/ussdmx?authSource=admin"

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      authentication-database: admin
      database: ussdmx
      host: 192.168.5.128
      port: 27017
      username: admin
      password: rw,.12a
      reactive: # Asegúrate de incluir esto para la configuración reactiva
        enabled: true
  codec:
    max-in-memory-size: 10MB

management:
  metrics:
    enable:
      jvm: false
      tomcat: false
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,loggers,scheduledtasks,metrics,configprops,quartz,refresh
    enabled-by-default: false
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
