
package com.hacom.ussdmxaprovisionamiento.xml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProvisioningPort", targetNamespace = "http://www.example.com/provisioning")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProvisioningPort {


    /**
     * 
     * @param methodCall
     * @return
     *     returns com.example.provisioning.MethodCallResponse
     */
    @WebMethod(action = "http://www.example.com/provisioning/saveProvisioning")
    @WebResult(name = "MethodCallResponse", targetNamespace = "http://www.example.com/provisioning", partName = "response")
    public MethodCallResponse saveProvisioning(
        @WebParam(name = "MethodCallRequest", targetNamespace = "http://www.example.com/provisioning", partName = "methodCall")
        MethodCallRequest methodCall);

}
